routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DownloadsController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\WikiController;
use App\Models\Version;
use App\Models\VersionGroup;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WikiController::class, 'home'])->name('home');

Route::get('/tag/{tag}', [TagController::class, 'view'])->where(['tag'], '[a-zA-Z0-9_]+')->name('tag');
Route::get('/category/{registry}', [CategoryController::class, 'view'])->where(['registry'], '[a-zA-Z0-9_]+')->name('category');

Route::get('/random', [ArticleController::class, 'random'])->name('random');

Route::get('/downloads', [DownloadsController::class, 'home'])->name('downloads');
Route::get('/downloads/nightly', [DownloadsController::class, 'nightly'])->name('nightly');
Route::get('/downloads/build/{build}', [DownloadsController::class, 'build'])->whereNumber(['build'])->name('build');
Route::get('/downloads/source/{build}', [DownloadsController::class, 'source'])->whereNumber(['build'])->name('source');

Route::get('/search', [ArticleController::class, 'search'])->name('search');

Route::get('/all', [ArticleController::class, 'list'])->name('all');

Route::get('/{slug1}/{slug2}', [ArticleController::class, 'view'])->where(['slug1', 'slug2'], '[a-zA-Z0-9_]+')->name('article');

//require __DIR__.'/auth.php';

app/Models/Ingredient.php
<?php

namespace App\Models;

use App\Handlers\Fragment\LinkFragmentHandler;
use App\Handlers\Fragment\TextFragmentHandler;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Config;
use Jenssegers\Model\Model;

class Ingredient extends Model {

    protected $fillable = ['item', 'tag', 'name', 'count', 'link', 'vararg'];

    public static function renderSlot(?Ingredient $inside, string $class = 'gui-slot gui-slot-back') : string {
        return '<div class="' . $class . '">' . ($inside ? $inside->insideSlot() : '') . '</div>';
    }

    public function getIdAttribute() : ?string {
        return $this->item;
    }

    public function getNamespaceAttribute() : ?string {
        if (!$this->item) return null;
        return explode(':', $this->item, 2)[0];
    }

    public function getPathAttribute() : ?string {
        if (!$this->item) return null;
        return explode(':', $this->item, 2)[1];
    }

    public function setTagFrom(array $tags) : Ingredient {
        if (!$this->item && $this->tag) {
            return new MultiIngredient(collect($tags[$this->tag])->map(fn($ing) => Ingredient::fromArray(array_replace($this->attributesToArray(), $ing)))->all());
        }
        return $this;
    }

    public function setNameFrom(array $translations) : Ingredient {
        if ($this->item) {
            $this->name = $translations[$this->item];
        }
        return $this;
    }

    public function setLinkFrom(array $links) : Ingredient {
        if ($this->item) {
            $this->link = $links[$this->item] ?? null;
        }
        return $this;
    }

    public function insideSlot() : string {
        $content = '';
        if ($this->item) {
            $block = 'images/models/' . $this->namespace . '/block/' . $this->path . '.png';
            $item = 'images/models/' . $this->namespace . '/item/' . $this->path . '.png';
            $asset = file_exists(public_path() . '/' . $block) ? $block : $item;
            $name = ($this->name != null) ? TextFragmentHandler::displayText($this->name) : null;
            $content .= '<img class="gui-ingredient" src="' . asset($asset) . '" alt="' . $name . '" data-mctooltip="' . $name . '">';
        }
        if ($this->link) {
            $properties = LinkFragmentHandler::getLinkProperties($this->link);
            $content = "<a target='{$properties['target']}' href='{$properties['href']}'>" . $content . '</a>';
        }
        if ($this->vararg) $this->count = '...';
        if (!is_numeric($this->count) || $this->count > 1) {
            $content .= '<span class="gui-stack-count mc-text">' . $this->count . '</span>';
        }
        return $content;
    }

    public static function fromArray($arr) : Ingredient {
        if (Arr::isAssoc($arr)) {
            return new Ingredient($arr);
        } else {
            return new MultiIngredient(collect($arr)->map(fn(array $ing) => new Ingredient($ing))->all());
        }
    }

}

app/View/Components/Alerts.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Alerts extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return string
     */
    public function render()
    {
        $content = '';
        if (session()->has("alert-yellow")) {
            $content .= '<div class="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4" role="alert">
                <p>' . session('alert-yellow') . '</p>
            </div>';
        }
        return $content;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/article.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col md:flex-row items-center text-center md:text-left">
            @if ($info)
                <div class="wiki-header-image flex-grow-0 flex-shrink-0">{!! \Illuminate\Support\Arr::pull($info, 'Image') !!}</div>
            @endif
            <div class="{{ $info ? 'border-gray-400 md:border-l-2 md:pl-4 md:ml-1 py-3' : '' }}">
                <h1 class="font-semibold font-bold text-4xl text-gray-800 leading-tight">
                    {{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($article->name) }}
                </h1>
                <span class="text-gray-500"><i class="{!! __('wiki.icons.registry.' . $article->slug1) !!}"></i>{{ ucwords(str_replace('_', ' ', $article->slug1)) }}</span>
                <aside>
                    <div>
                        @foreach ($main as $section)
                            <a href="#section-{{ $section->id }}" title="{{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($section->name) }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">{{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($section->name) }}</a>
                            @if (!$loop->last)
                                <span class="wiki-separator">-</span>
                            @endif
                        @endforeach
                    </div>
                </aside>
            </div>
        </div>
        @if ($info)
            @php
                $colors = \Illuminate\Support\Arr::pull($info, 'Map Colors');
                $reqtool = \Illuminate\Support\Arr::pull($info, 'Required Tool');
                if ($reqtool) $tool = ['Required', $reqtool];
                $rectool = \Illuminate\Support\Arr::pull($info, 'Recommended Tool');
                if ($rectool) $tool = ['Recommended', $rectool];
            @endphp
            <div class="mt-2 flex flex-wrap gap-1 text-xs sm:text-sm">
                @foreach ($info as $k => $v)
                    <div class="rounded-xl bg-gray-200 py-0.5 px-2.5 flex items-center">
                        <div class="font-bold mr-1">{!! $k !!}:</div>
                        <div>{!! $v !!}</div>
                    </div>
                @endforeach
            </div>
            @if ($tool ?? null)
                <div class="mt-2 flex flex-wrap gap-1">
                    <div class="flex items-center">
                        <div class="font-bold mr-2">{!! $tool[0] !!} Tool:</div>
                        <div>{!! $tool[1] !!}</div>
                    </div>
                </div>
            @endif
            @if ($colors)
                <div class="mt-2 flex flex-wrap gap-1">
                    <div class="flex items-center">
                        <div class="font-bold mr-2">Map Color{{ substr_count($colors, '<div class="wiki-color">') > 1 ? 's' : '' }}:</div>
                        <div>{!! $colors !!}</div>
                    </div>
                </div>
            @endif
        @endif
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <x-alerts />
                <div class="p-6 bg-white border-b border-gray-200">
                    @foreach ($main as $section)
                        <h2 id="section-{{ $section->id }}" class="font-semibold text-2xl">{{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($section->name) }}</h2>
                        @foreach ($section->fragments as $fragment)
                            {!! \App\Handlers\Fragment\FragmentHandler::render($fragment->markup, function(string $content, array $markup, string $class) {
                                return $class::getOuterMarkup($content, $markup);
                            }, $fragment) !!}
                        @endforeach
                    @endforeach
                </div>
                <div class="p-6 bg-white border-b border-gray-200">
                    @if ($article->tags)
                        <div class="flex gap-1 items-center mb-1">
                            <span>Tags: </span>
                            <div class="flex flex-wrap gap-1">
                                @foreach ($article->tags as $tag)
                                    <a href="{{ route('tag', ['tag' => \Illuminate\Support\Str::snake(strtolower($tag->tag))]) }}" class="rounded-xl bg-blue-400 hover:bg-blue-600 visited:bg-blue-500 text-white py-0.5 px-2.5 flex items-center">
                                        <div>{{ $tag->tag }}</div>
                                    </a>
                                @endforeach
                            </div>
                        </div>
                    @endif
                    <div>
                        <a href="{{ route('category', ['registry' => $article->slug1]) }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">
                            View all {{ str_replace('_', ' ', $article->slug1) }} articles.
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/downloads.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('wiki.page.downloads') }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <x-alerts />
                <div class="p-6 bg-white border-b border-gray-200">
                    <p class="pb-2 text-center">
                        Below is a list of major versions, <a href="{{ route('nightly') }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">click here</a> for nightly builds.
                    </p>

                    @foreach ($groups as $k => $group)
                        <h1 class="font-semibold text-2xl mb-2">{{ $group->name }}</h1>
                        <div class="text-center mb-3">
                            @foreach ($group->versions as $k2 => $version)
                                @php ($build = $version->builds->last())
                                @if (!$build) @continue @endif
                                <div class="w-full lg:flex justify-center items-center">
                                    <div class="inline-flex items-center lg:my-1 my-2">
                                        @if ($version->title)
                                            <span class="mr-2">{{ $version->title }}</span>
                                        @endif
                                        <a href="{{ route('build', $build) }}" class="
                                            @if ($k === 0 && $k2 === 0)
                                                bg-green-500 hover:bg-green-700 py-2 px-4 text-lg
                                            @else
                                                bg-blue-600 hover:bg-blue-800 py-1.5 px-3
                                            @endif
                                        text-white rounded inline-flex items-center">
                                            <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z"/></svg>
                                            <span>{{ $version->mod_version }}</span>
                                            @if ($k === 0 && $k2 === 0)
                                                <span class="opacity-80 ml-1 text-gray-200 font-extrabold">(latest)</span>
                                            @endif
                                        </a>
                                        @if ($build->source_path)
                                            <a href="{{ route('source', $build) }}" class="ml-1.5 text-gray-500 hover:text-gray-300">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
                                                </svg>
                                            </a>
                                        @endif
                                    </div>
                                    <p class="ml-1.5">
                                        for Minecraft {{ $version->mc_version }}, released <span class="border-dashed border-black border-b" title="{{ $version->released_at->format('d/m/Y H:i:s') }}">{{ $version->released_at->diffForHumans() }}</span>
                                    </p>
                                </div>
                            @endforeach
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('wiki.page.home') }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <x-alerts />
                <div class="p-6 bg-white border-b border-gray-200 text-center">
                    <h1 class="text-2xl mt-6 mb-12">Welcome to the Loosely Connected Concepts Wiki, serving <a class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600" href="{{ route('all') }}">{{ $articles }} pages</a>.</h1>

                    <div class="grid md:grid-cols-5 sm:grid-cols-3 grid-cols-2 gap-x-2">
                        @foreach (['Wasteland', 'Power', 'Nuclear', 'Materials', 'Nostalgic'] as $card)
                            <a href="{{ route("article", ['slug1' => 'concept', 'slug2' => strtolower($card)]) }}" class="overflow-hidden wiki-card text-indigo-500 hover:text-indigo-800 visited:text-indigo-600">
                                <div class="rounded w-full wiki-card-img" style="background-image: url('/images/cards/{{ strtolower($card) }}.png');"></div>
                                <div class="text-2xl p-2">{{ $card }}</div>
                            </a>
                        @endforeach
                    </div>

                    <h2 class="text-lg my-12">The current version of the mod is <a class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600" href="{{ route('article', ['slug1' => 'version', 'slug2' => $current->code]) }}">LCC {{ $current->mod_version }}</a>, which can be downloaded <a class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600" href="{{ route('build', $current->builds[0]) }}">here</a>.</h2>

                    <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1">
                        <div class="">
                            <div class="text-2xl font-bold my-3">
                                <i class="fas fa-tags fa-fw"></i>
                                Tags
                            </div>
                            <div class="text-left">
                                @foreach ($tags as $tag)
                                    <p><a href="{{ route("tag", ['tag' => \Illuminate\Support\Str::snake(strtolower($tag))]) }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">{{ $tag }}</a></p>
                                @endforeach
                            </div>
                        </div>
                        <div class="">
                            <div class="text-2xl font-bold my-3">
                                <i class="fas fa-layer-group fa-fw"></i>
                                Categories
                            </div>
                            <div class="text-left">
                                @foreach ($registries as $registry)
                                    <p><a href="{{ route("category", ['registry' => $registry]) }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">{{ trans_choice('wiki.category.name.' . $registry, 2) }}</a></p>
                                @endforeach
                            </div>
                        </div>
                        <div class="">
                            <div class="text-2xl font-bold my-3">
                                <i class="fas fa-fire fa-fw"></i>
                                Popular Pages
                            </div>
                            <div class="text-left">
                                @foreach ($popular as $article)
                                    <div class="grid" style="grid-template-columns: 1fr auto;">
                                        <a href="{{ route("article", ['slug1' => $article->slug1, 'slug2' => $article->slug2]) }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">{{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($article->name) }}</a>
                                        <p>{{ $article->counter }}</p>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="">
                            <div class="text-2xl font-bold my-3">
                                <i class="fas fa-book fa-fw"></i>
                                Guides
                            </div>
                            <div class="text-left">
                                @foreach ($guides as $article)
                                    <p><a href="{{ route("article", ['slug1' => $article->slug1, 'slug2' => $article->slug2]) }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">{{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($article->name) }}</a></p>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col md:flex-row items-center text-center md:text-left">
            <div>
                <h1 class="font-semibold font-bold text-4xl text-gray-800 leading-tight">{{ $title }}</h1>
                @if ($type ?? null)
                    <span class="text-gray-500"><i class="{!! __('wiki.icons.' . $type) !!}"></i>{{ __('wiki.list.type.' . $type) }}</span>
                @endif
            </div>
        </div>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <x-alerts />
                <div class="p-6 bg-white border-b border-gray-200">
                    <h2 class="font-semibold text-xl mb-4">{{ trans_choice('wiki.list.matches.' . $matches, $articles->count()) }}</h2>
                    {!! \App\Handlers\Fragment\FragmentHandler::renderArticleList($articles->each(function(\App\Models\Article $article) { $article->link = true; })) !!}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/nightly.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('wiki.page.downloads') }}
        </h2>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <x-alerts />
                <div class="p-6 bg-white border-b border-gray-200">
                    <p class="pb-2 text-center">
                        Below is a list of nightly builds, these versions are <span class="font-extrabold text-red-800">in progress</span> and are likely to be <span class="font-extrabold text-red-800">not fully functional</span> and <span class="font-extrabold text-red-800">subject to change</span>. - Download at your own risk.<br><a href="{{ route('downloads') }}" class="underline text-blue-500 hover:text-blue-800 visited:text-blue-600">Click here</a> for regular builds.
                    </p>

                    <div class="text-center mb-3">
                        @foreach ($builds as $k => $build)
                            <div class="w-full lg:flex justify-center items-center">
                                <div class="inline-flex items-center lg:my-1 my-2">
                                    <a href="{{ route('build', $build) }}" class="
                                        @if ($k === 0)
                                            bg-red-600 hover:bg-red-800 py-2 px-4 text-lg
                                        @else
                                            bg-gray-800 hover:bg-gray-900 py-1.5 px-3
                                        @endif
                                    text-white rounded inline-flex items-center">
                                        <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z"/></svg>
                                        <span>Build {{ $build->run_number }}</span>
                                        @if ($k === 0)
                                            <span class="opacity-60 ml-1 text-gray-200 font-extrabold">(latest)</span>
                                        @endif
                                    </a>
                                    @if ($build->source_path)
                                        <a href="{{ route('source', $build) }}" class="ml-1.5 text-gray-500 hover:text-gray-300">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
                                            </svg>
                                        </a>
                                    @endif
                                </div>
                                <p class="ml-1.5">
                                    for Minecraft {{ $build->mc_version }}, built <span class="border-dashed border-black border-b" title="{{ $build->created_at->format('d/m/Y H:i:s') }}">{{ $build->created_at->diffForHumans() }}</span> from branch '{{ $build->ref_name }}'.
                                </p>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/search.blade.php
<x-app-layout>
    <x-slot name="header">
        <h1 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('wiki.page.search', ['for' => $query]) }}
        </h1>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <x-alerts />
                <div class="p-6 bg-white border-b border-gray-200">
                    @if (!$matches && !$similars)
                        <p>{{ __('wiki.search.none') }}</p>
                    @elseif ($matches)
                        <h2 class="font-semibold text-2xl mb-2">{{ trans_choice('wiki.search.matches', count($matches)) }}</h2>
                    @endif
                    @foreach ($matches as $match)
                        <a class="wiki-search-result max-w-sm w-full lg:max-w-full mb-4 border border-gray-300 bg-white rounded text-indigo-500 hover:text-indigo-800 visited:text-indigo-600 flex" href="{{ route('article', ['slug1' => $match->slug1, 'slug2' => $match->slug2]) }}">
                            @if ($match->image !== null)
                                <div class="wiki-search-image bg-gray-200" style="background-image: url('{{ $match->image }}')"></div>
                            @endif
                            <div class="px-4 py-3 flex-grow flex flex-col leading-normal w-full border-gray-400 border-l-4">
                                <div class="font-bold text-xl mb-1">{{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($match->name) }}</div>
                                <p class="text-gray-700 text-base">{{ $match->excerpt }}</p>
                            </div>
                        </a>
                    @endforeach
                    @if ($similars)
                        <h2 class="font-semibold text-2xl mb-2">{{ trans_choice('wiki.search.similar', count($similars)) }}</h2>
                    @endif
                    @foreach ($similars as $similar)
                        <a class="wiki-search-result max-w-sm w-full lg:max-w-full mb-4 border border-gray-300 bg-white rounded text-indigo-500 hover:text-indigo-800 visited:text-indigo-600 flex" href="{{ route('article', ['slug1' => $similar->slug1, 'slug2' => $similar->slug2]) }}">
                            @if ($similar->image !== null)
                                <div class="wiki-search-image bg-gray-200" style="background-image: url('{{ $similar->image }}')"></div>
                            @endif
                            <div class="px-4 py-3 flex-grow flex flex-col leading-normal w-full border-gray-400 border-l-4">
                                <div class="font-bold text-xl mb-1">{{ \App\Handlers\Fragment\TextFragmentHandler::displayJsonText($similar->name) }}</div>
                                <p class="text-gray-700 text-base">{{ $similar->excerpt }}</p>
                            </div>
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>